<a href="https://colab.research.google.com/github/hhc703/PyTorch/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Regression

In [ ]:
import torch

In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[4], [5], [6]])

In [ ]:
w = torch.zeros(1, requires_grad=True)  #requires_grad : 학습을 통해 변경되는 값임을 명시.
b = torch.zeros(1, requires_grad=True)

In [ ]:
optimizer = torch.optim.SGD([w, b], lr=0.01)  # Stochastic Gradient Descent (확률적 경사 하강법) : 전체가 아닌 무작위로 배치 추출

In [ ]:
epochs = 1000

for epoch in range(1, epochs + 1):
  #학습값
  hypothesis = x_train * w + b

  #mse : mean squared error
  cost = torch.mean((hypothesis - y_train) ** 2)

  #이전 루프의 grad가 간섭하는 일이 발생하지 않게 하기 위해 초기화
  optimizer.zero_grad()
  #비용 함수 미분하여 grad계산
  cost.backward()
  #w와 b 업데이트
  optimizer.step()

In [ ]:
print(w, b) #반복 결과 w : 1, b : 2.98 결과 얻음

tensor([1.0850], requires_grad=True) tensor([2.8067], requires_grad=True)


Multivariate Linear Regression

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 83],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
#모델 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, out_dim=1
model = nn.Linear(3, 1)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.5435,  0.3462, -0.1188]], requires_grad=True), Parameter containing:
tensor([0.2937], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(),lr=1e-5)

In [ ]:
epochs = 2000
for epoch in range(epochs + 1):
  prediction = model(x_train)
  #model.forward(x_train)

  cost = F.mse_loss(prediction, y_train) #평균 제곱 오차 함수

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

In [ ]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print(pred_y)

tensor([[154.8465]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7351, 0.9024, 0.3825]], requires_grad=True), Parameter containing:
tensor([0.3057], requires_grad=True)]
